In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
automobiles_data = pd.read_csv('datasets/CarPrice_Assignment.csv')

automobiles_data.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [3]:
automobiles_data.shape

(205, 26)

In [4]:
automobiles_data.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [5]:
automobiles_data.drop(['car_ID', 'symboling', 'CarName'], axis=1, inplace=True)

In [6]:
automobiles_data = pd.get_dummies(automobiles_data)

In [7]:
automobiles_data.head()

wheelbase  carlength  carwidth  carheight  curbweight  enginesize  \
0       88.6      168.8      64.1       48.8        2548         130   
1       88.6      168.8      64.1       48.8        2548         130   
2       94.5      171.2      65.5       52.4        2823         152   
3       99.8      176.6      66.2       54.3        2337         109   
4       99.4      176.6      66.4       54.3        2824         136   

   boreratio  stroke  compressionratio  horsepower  ...  \
0       3.47    2.68               9.0         111  ...   
1       3.47    2.68               9.0         111  ...   
2       2.68    3.47               9.0         154  ...   
3       3.19    3.40              10.0         102  ...   
4       3.19    3.40               8.0         115  ...   

   cylindernumber_twelve  cylindernumber_two  fuelsystem_1bbl  \
0                      0                   0                0   
1                      0                   0                0   
2                      0                   0                0   
3                      0                   0                0   
4                      0                   0                0   

   fuelsystem_2bbl  fuelsystem_4bbl  fuelsystem_idi  fuelsystem_mfi  \
0                0                0               0               0   
1                0                0               0               0   
2                0                0               0               0   
3                0                0               0               0   
4                0                0               0               0   

   fuelsystem_mpfi  fuelsystem_spdi  fuelsystem_spfi  
0                1                0                0  
1                1                0                0  
2                1                0                0  
3                1                0                0  
4                1                0                0  

[5 rows x 52 columns]

In [8]:
automobiles_data.shape

(205, 52)

In [9]:
X = automobiles_data.drop('price', axis=1)

Y = automobiles_data['price']

In [10]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [11]:
x_train.shape, x_test.shape

((164, 51), (41, 51))

In [12]:
y_train.shape, y_test.shape

((164,), (41,))

In [13]:
model = LinearRegression().fit(x_train, y_train)

In [14]:
Training_score = model.score(x_train, y_train)

Training_score

0.9398595696065082

In [15]:
y_pred = model.predict(x_test)

y_pred

array([36265.2719693 ,  6732.93101583,  6452.17332767, 26468.64230247,
        6434.91263717,  7487.73075351,  8522.29034606, 18731.11537308,
       16830.72412546, 18731.11537308, 10298.5178323 ,  7179.84267767,
        6790.8579247 , 19662.75446991,  6440.69270258,  9724.30942008,
       10977.04521781, 16080.53825537, 10709.61958422,  9637.47167142,
       18502.17479528, 10285.9349866 ,  2471.33689341,  6906.11987288,
        7341.51255452,  9115.33817298,  5981.96734697, 10999.82928169,
       14015.11391663, 17281.12068244, 10011.54370265, 13088.63937606,
        8405.15678527,  7362.74346096, 15996.06796403,  7373.90621197,
       27474.49765987,  6688.6647532 , 14843.66865217,  7101.91258328,
       35509.12024699])

In [16]:
Testing_score = r2_score(y_test, y_pred)

Testing_score

0.8914069949021312

### Serializing and storing data model using JSON

In [42]:
import json

In [18]:
model.coef_

array([ 5.76411383e+00, -8.15487674e+01,  6.32888043e+02,  9.89906539e+01,
        4.16255596e+00,  1.27184215e+02,  2.27840639e+03, -5.77754148e+03,
       -1.36372881e+03, -1.63890881e+01,  2.68526640e+00, -1.62376795e+02,
        2.07725624e+02,  6.76936229e+03, -6.76936229e+03, -8.91243760e+02,
        8.91243760e+02, -1.23941315e+02,  1.23941315e+02,  1.60859815e+03,
       -4.39369630e+02, -8.25529097e+02,  1.81176216e+02, -5.24875644e+02,
        1.59531082e+02,  4.13091820e+01, -2.00840264e+02, -4.12933244e+03,
        4.12933244e+03,  2.05344115e+03, -6.00628125e+03,  1.28640156e+03,
        4.73925370e+03,  1.42882028e+02, -6.06663184e+03,  3.85093465e+03,
        7.37083555e+03, -5.08420731e+03, -5.73709381e+03, -4.00469073e+02,
        0.00000000e+00,  0.00000000e+00,  3.85093465e+03,  8.85332864e+02,
        2.88945333e+02, -1.88210607e+03,  6.76936229e+03, -3.85127140e+03,
        2.48334853e+02, -2.65861428e+03,  2.00016407e+02])

In [19]:
model.intercept_

-25493.101073339105

In [20]:
model_param = {}

model_param['coef'] = list(model.coef_)
model_param['intercept'] = model.intercept_.tolist()

In [21]:
json_txt = json.dumps(model_param, indent=4)

json_txt

'{\n    "coef": [\n        5.764113828653719,\n        -81.54876742428226,\n        632.8880427198162,\n        98.99065391709442,\n        4.162555960025178,\n        127.1842152520622,\n        2278.4063877397866,\n        -5777.5414789275865,\n        -1363.7288068145021,\n        -16.389088109002383,\n        2.6852664042756795,\n        -162.37679474106454,\n        207.72562444748962,\n        6769.362291766622,\n        -6769.362291766626,\n        -891.2437600600078,\n        891.2437600600632,\n        -123.94131505077318,\n        123.9413150507845,\n        1608.5981548388063,\n        -439.3696299082146,\n        -825.5290965196755,\n        181.17621555371468,\n        -524.8756439646208,\n        159.531081809691,\n        41.30918203027005,\n        -200.8402638399663,\n        -4129.33243943784,\n        4129.332439437834,\n        2053.4411503649894,\n        -6006.281245322347,\n        1286.4015642509323,\n        4739.253698446523,\n        142.88202768237818,\n    

In [22]:
with open('models/regressor_param.txt', 'w') as file:
    
    file.write(json_txt)

In [23]:
with open('models/regressor_param.txt', 'r') as file:
    
    json_text=json.load(file)

In [24]:
json_model = LinearRegression()

In [25]:
json_model.coef_ = np.array(json_text['coef'])
json_model.intercept_ = np.array(json_text['intercept'])

In [26]:
y_pred = json_model.predict(x_test)

r2_score(y_test, y_pred)

0.8914069949021312

In [27]:
Testing_score

0.8914069949021312

### Serializing and storing data model using pickle

In [41]:
# Module which implements protocols for serializing and deserializing
# Python objects to a bytestream - pickling and unpickling objects
import pickle

In [29]:
pickle.dump(model, open('models/model.pkl', 'wb'))

In [30]:
pickle_model = pickle.load(open('models/model.pkl', 'rb'))

In [31]:
y_pred = pickle_model.predict(x_test)

y_pred

array([36265.2719693 ,  6732.93101583,  6452.17332767, 26468.64230247,
        6434.91263717,  7487.73075351,  8522.29034606, 18731.11537308,
       16830.72412546, 18731.11537308, 10298.5178323 ,  7179.84267767,
        6790.8579247 , 19662.75446991,  6440.69270258,  9724.30942008,
       10977.04521781, 16080.53825537, 10709.61958422,  9637.47167142,
       18502.17479528, 10285.9349866 ,  2471.33689341,  6906.11987288,
        7341.51255452,  9115.33817298,  5981.96734697, 10999.82928169,
       14015.11391663, 17281.12068244, 10011.54370265, 13088.63937606,
        8405.15678527,  7362.74346096, 15996.06796403,  7373.90621197,
       27474.49765987,  6688.6647532 , 14843.66865217,  7101.91258328,
       35509.12024699])

In [32]:
r2_score(y_test, y_pred)

0.8914069949021312

In [33]:
Testing_score

0.8914069949021312

### Serializing and storing data model using JobLib

The joblib module is better fit for serializing scikit-learn
models as it works more efficiently with objects that
have large NumPy arrays internally


In [34]:
import joblib

In [35]:
filename = 'models/model.joblib'

In [36]:
joblib.dump(model, filename)

['models/model.joblib']

In [37]:
joblib_model = joblib.load(filename)

In [38]:
y_pred = joblib_model.predict(x_test)

y_pred

array([36265.2719693 ,  6732.93101583,  6452.17332767, 26468.64230247,
        6434.91263717,  7487.73075351,  8522.29034606, 18731.11537308,
       16830.72412546, 18731.11537308, 10298.5178323 ,  7179.84267767,
        6790.8579247 , 19662.75446991,  6440.69270258,  9724.30942008,
       10977.04521781, 16080.53825537, 10709.61958422,  9637.47167142,
       18502.17479528, 10285.9349866 ,  2471.33689341,  6906.11987288,
        7341.51255452,  9115.33817298,  5981.96734697, 10999.82928169,
       14015.11391663, 17281.12068244, 10011.54370265, 13088.63937606,
        8405.15678527,  7362.74346096, 15996.06796403,  7373.90621197,
       27474.49765987,  6688.6647532 , 14843.66865217,  7101.91258328,
       35509.12024699])

In [39]:
r2_score(y_test, y_pred)

0.8914069949021312

In [40]:
Testing_score

0.8914069949021312